/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedExpensesImport } from './routes/_authed/expenses'
import { Route as AuthedCreateExpenseImport } from './routes/_authed/create-expense'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedExpensesRoute = AuthedExpensesImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCreateExpenseRoute = AuthedCreateExpenseImport.update({
  id: '/create-expense',
  path: '/create-expense',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authed/create-expense': {
      id: '/_authed/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof AuthedCreateExpenseImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/expenses': {
      id: '/_authed/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthedExpensesImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedCreateExpenseRoute: typeof AuthedCreateExpenseRoute
  AuthedExpensesRoute: typeof AuthedExpensesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateExpenseRoute: AuthedCreateExpenseRoute,
  AuthedExpensesRoute: AuthedExpensesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/create-expense': typeof AuthedCreateExpenseRoute
  '/expenses': typeof AuthedExpensesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/create-expense': typeof AuthedCreateExpenseRoute
  '/expenses': typeof AuthedExpensesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authed/create-expense': typeof AuthedCreateExpenseRoute
  '/_authed/expenses': typeof AuthedExpensesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about' | '/create-expense' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/create-expense' | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/_authed/create-expense'
    | '/_authed/expenses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/create-expense",
        "/_authed/expenses"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authed/create-expense": {
      "filePath": "_authed/create-expense.tsx",
      "parent": "/_authed"
    },
    "/_authed/expenses": {
      "filePath": "_authed/expenses.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
